### ISSUE TITLE
mysql image throws an error

### ISSUE THREAD

**Issue by jakemackie** [jakemackie/wordpress#10]
```bash
2024-06-09T15:50:18.502453Z 12 [Note] Access denied for user 'root'@'localhost' (using password: NO)
```

Likely due to docker-compose file, though credentials are consistent. Further debugging is needed

**Comment by jakemackie** [comment]
Gonna take a break, at least the Wordpress image works now. Hopefully as soon as we tackle this we can actually see our page 😆

**Comment by alfiephillips** [comment]
> ```bash
> 
> 2024-06-09T15:50:18.502453Z 12 [Note] Access denied for user 'root'@'localhost' (using password: NO)
> 
> ```
> 
> 
> 
> Likely due to docker-compose file, though credentials are consistent. Further debugging is needed

Yeah this is the exact issue I had you've replicated here, something strange is going on in the bash script that makes it not use a password when trying to authenticate. I explicitly specified to use the root password and it doesn't recognise it.

**Comment by alfiephillips** [comment]
> Gonna take a break, at least the Wordpress image works now. Hopefully as soon as we tackle this we can actually see our page 😆

Would be great to actually see the website 😭

**Comment by jakemackie** [comment]
> > ```shell
> > 2024-06-09T15:50:18.502453Z 12 [Note] Access denied for user 'root'@'localhost' (using password: NO)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Likely due to docker-compose file, though credentials are consistent. Further debugging is needed
> 
> Yeah this is the exact issue I had you've replicated here, something strange is going on in the bash script that makes it not use a password when trying to authenticate. I explicitly specified to use the root password and it doesn't recognise it.

I can only guess we've configured the mysql service wrong somehow, even though the environment variables are set it's clearly not using them, I'll take a look later. For now? Coffee break

**Comment by alfiephillips** [comment]
> > > ```shell
> 
> > > 2024-06-09T15:50:18.502453Z 12 [Note] Access denied for user 'root'@'localhost' (using password: NO)
> 
> > > ```
> 
> > > 
> 
> > > 
> 
> > >     
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >     
> 
> > >   
> 
> > > Likely due to docker-compose file, though credentials are consistent. Further debugging is needed
> 
> > 
> 
> > Yeah this is the exact issue I had you've replicated here, something strange is going on in the bash script that makes it not use a password when trying to authenticate. I explicitly specified to use the root password and it doesn't recognise it.
> 
> 
> 
> I can only guess we've configured the mysql service wrong somehow, even though the environment variables are set it's clearly not using them, I'll take a look later. For now? Coffee break

Amen to that

**Comment by jakemackie** [comment]
Just thinking of how we could further test this. I've terminal output coming from the `setup.sh` file, which is great, it's finally found. I think the next thing we can and do is hard-code the database credentials in that setup file (which would be `wordpress` for everything lol) just to see once again if it's a case of it not reading the environment variables. If we're connected we know everything else works as expected. 

I can't debug this until later though, are you in college today?

**Comment by alfiephillips** [comment]
> Just thinking of how we could further test this. I have terminal output coming from the `setup.sh` file, which is great, it's finally found. I think the next thing we can and do is hard-code the database credentials in that setup file (which would be `wordpress` for everything lol) just to see once again if it's a case of it not reading the environment variables. If we're connected we know everything else works as expected. 
> 
> I can't debug this until later though, are you in college today?

That's a very good idea since it might just be a problem with initiating the environment variables, might aswell try it. Unfortunately I can't have a look till later got an exam today 😬

**Comment by jakemackie** [comment]
> > Just thinking of how we could further test this. I have terminal output coming from the `setup.sh` file, which is great, it's finally found. I think the next thing we can and do is hard-code the database credentials in that setup file (which would be `wordpress` for everything lol) just to see once again if it's a case of it not reading the environment variables. If we're connected we know everything else works as expected.
> > I can't debug this until later though, are you in college today?
> 
> That's a very good idea since it might just be a problem with initiating the environment variables, might aswell try it. Unfortunately I can't have a look till later got an exam today 😬

Good luck!

**Comment by alfiephillips** [comment]
No longer concerns the use of a **root** user - set up for database is working correctly 👍
