### ISSUE TITLE
Development vs Production: Environments

### ISSUE THREAD

**Issue by jakemackie** [jakemackie/wordpress#11]
After thinking about our current Docker setup, it would be beneficial to:
- copy the compiled `dist` folder in a production container where frontend changes __aren't__ made.
- use the `node` image to build tailwindcss in a development container, where frontend change __are__ made.

**Comment by jakemackie** [comment]
Thoughts on this? @alfiephillips

**Comment by alfiephillips** [comment]
> After thinking about our current Docker setup, it would be beneficial to:
> 
> - copy the compiled `dist` folder in a production container where frontend changes __aren't__ made.
> 
> - use the `node` image to build tailwindcss in a development container, where frontend change __are__ made.

Sounds good, need to also ensure we can develop and see live changes without having to re-initialize the container everytime we make a change.

We also want to make sure we manage our environment to detect if we're in production; for example there's some settings in **wp-config.php** for verbosity and deciding our site url etc.

We are also going to want to include webpack for the production environment.

**Comment by alfiephillips** [comment]
Closing this issue as removing all processes including **docker** and reverting to using **XAMPP** server.
