### ISSUE TITLE
Issue with wp-config

### ISSUE THREAD

**Issue by jakemackie** [jakemackie/wordpress#13]
Now that all Docker images are starting successfully, I turn to `wp-config`. I don't think it's reading envrionment variables correctly.

**Comment by alfiephillips** [comment]
Use of **get_env()** in [wp_config](https://github.com/jakemackie/wordpress/blob/wp-docker-bug/wp-config/wp-config.php) may be returning null, depending on if it can access the environment in the project root i'm not sure.

**Comment by jakemackie** [comment]
> Use of **get_env()** in [wp_config](https://github.com/jakemackie/wordpress/blob/wp-docker-bug/wp-config/wp-config.php) may be returning null, depending on if it can access the environment in the project root i'm not sure.

I hard coded it and it's no difference. What is interesting are the debug lines I added to the setup script, and you can clearly see:

```bash
2024-06-10 19:26:44 Starting setup script...
2024-06-10 19:26:44 Checking for required environment variables...
2024-06-10 19:26:44 WORDPRESS_DB_HOST: db:3306
2024-06-10 19:26:44 WORDPRESS_DB_USER: wordpress
2024-06-10 19:26:44 WORDPRESS_DB_PASSWORD: wordpress
2024-06-10 19:26:44 WORDPRESS_DB_NAME: wordpress
2024-06-10 19:26:44 mysqld is alive
2024-06-10 19:26:44 Database connection established.
2024-06-10 19:26:44 Creating database if it doesn't exist...
2024-06-10 19:26:44 Verifying database creation and permissions...
2024-06-10 19:26:44 Database wordpress exists and is accessible.
2024-06-10 19:26:44 Setup complete. Starting Apache..
```

![image](https://github.com/jakemackie/wordpress/assets/142145913/880e8523-1069-4e37-b70f-75427b0726b5)

**Comment by jakemackie** [comment]
> > Use of **get_env()** in [wp_config](https://github.com/jakemackie/wordpress/blob/wp-docker-bug/wp-config/wp-config.php) may be returning null, depending on if it can access the environment in the project root i'm not sure.
> 
> I hard coded it and it's no difference. What is interesting are the debug lines I added to the setup script, and you can clearly see:
> 
> ```shell
> 2024-06-10 19:26:44 Starting setup script...
> 2024-06-10 19:26:44 Checking for required environment variables...
> 2024-06-10 19:26:44 WORDPRESS_DB_HOST: db:3306
> 2024-06-10 19:26:44 WORDPRESS_DB_USER: wordpress
> 2024-06-10 19:26:44 WORDPRESS_DB_PASSWORD: wordpress
> 2024-06-10 19:26:44 WORDPRESS_DB_NAME: wordpress
> 2024-06-10 19:26:44 mysqld is alive
> 2024-06-10 19:26:44 Database connection established.
> 2024-06-10 19:26:44 Creating database if it doesn't exist...
> 2024-06-10 19:26:44 Verifying database creation and permissions...
> 2024-06-10 19:26:44 Database wordpress exists and is accessible.
> 2024-06-10 19:26:44 Setup complete. Starting Apache..
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/142145913/338301894-880e8523-1069-4e37-b70f-75427b0726b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNDQ2NzIsIm5iZiI6MTcxODA0NDM3MiwicGF0aCI6Ii8xNDIxNDU5MTMvMzM4MzAxODk0LTg4MGU4NTIzLTEwNjktNGUzNy1iNzBmLTc1NDI3YjA3MjZiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQxODMyNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjE2ZTdmOWI0OWFmNzc4Nzk1Mjk1NjBkYWU5YmExMzNiYWVmZmMzNTgzNzA2NzJiNGI5ZmE1NTVhYmRjYmQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SgyuYjKMsA72W78_Z1meXljznzZvVtHhHbmTIgf21uE)

Adding to this - the `.env` file isn't needed. The variables in the compose file are being recognised in all areas of the app, apart from `wp-config`, I believe.

**Comment by alfiephillips** [comment]
Closing this issue as removing all processes including **docker** and reverting to using **XAMPP** server.
