### ISSUE TITLE
Ignore the dist folder

### ISSUE THREAD

**Issue by jakemackie** [jakemackie/wordpress#2]
Tailwind's build files should not be included

**Comment by alfiephillips** [comment]
> Tailwind's build files should not be included

still awake? same

Nice work we have a good boilerplate to work with 👍

**Comment by jakemackie** [comment]
> > Tailwind's build files should not be included
> 
> still awake? same
> 
> Nice work we have a good boilerplate to work with 👍

Haha you are? I just realised I've messed up big time

I need to move the git repo over to our theme, not the entire WordPress installation...

**Comment by alfiephillips** [comment]
> > > Tailwind's build files should not be included
> 
> > 
> 
> > still awake? same
> 
> > 
> 
> > Nice work we have a good boilerplate to work with 👍
> 
> 
> 
> Haha you are? I just realised I've messed up big time
> 
> 
> 
> I need to move the git repo over to our theme, not the entire WordPress installation...

I think this is where we bring in docker right, so we can be building a Wordpress installation that's consistent across both our machines rather than relying on github to hold all of it. Am i right?

**Comment by jakemackie** [comment]
> > > > Tailwind's build files should not be included
> > 
> > 
> > > 
> > 
> > 
> > > still awake? same
> > 
> > 
> > > 
> > 
> > 
> > > Nice work we have a good boilerplate to work with 👍
> > 
> > 
> > Haha you are? I just realised I've messed up big time
> > I need to move the git repo over to our theme, not the entire WordPress installation...
> 
> I think this is where we bring in docker right, so we can be building a Wordpress installation that's consistent across both our machines rather than relying on github to hold all of it. Am i right?
> 
> And yeah, probably best we stick to keeping it within our theme then we won't have to worry about ignoring so many files (literally thousands)

Sorted the git tracking now. And yes I agree, adding docker early makes sense.
